name: Frog
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51449
title: asdad
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#673713'
    - '#ebedea'
    - '#2a0d09'
    - '#afaba0'
    - '#ef982d'
  brandStrength: 0.9375
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
