name: Frog
favicon: null
layout_spectrum: 0.22919
typography_spectrum: 0.381
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#383939'
    - '#92CEFF'
    - '#FFD89A'
    - '#77FFB6'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
